music/urls.py
from django.urls import path
from . import views
app_name='music'
urlpatterns = [
    path('',views.index,name="index"),
    path('<int:album_id>/',views.details, name='details'),
    path('<int:album_id>/favourite/',views.favourite, name='favourite')
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/',include('music.urls'))
]

music/models.py
from django.db import models

class Album(models.Model):
    artist=models.CharField(max_length=300)
    album_title=models.CharField(max_length=150)
    genre=models.CharField(max_length=100)
    album_logo=models.CharField(max_length=10000)
    def __str__(self):
        return self.artist+'-'+self.album_title+'-'+self.genre+'-'+self.album_logo

class Song(models.Model):
    album=models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type=models.CharField(max_length=10)
    song_title=models.CharField(max_length=250)
    is_favourite=models.BooleanField(default=False)
    def __str__(self):
        return self.file_type +'-'+ self.song_title
# Create your models here.

music/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from django.http import Http404
from .models import Album,Song
from django.template import loader

def index(request):
    all_albums=Album.objects.all()
    #template=loader.get_template('music/index.html')
    context={'all_albums':all_albums,}
    #return HttpResponse(template.render(context,request))
    return render(request,'music/index.html',context)

#def details(request ,album_id):
    #return HttpResponse("Album Request=>" + str(album_id) )

#raising a Http404 Error
def details(request,album_id):
    album=get_object_or_404(Album,pk=album_id)
    '''try:
        album=Album.objects.get(pk=album_id)
    except Album.DoesNotExist:
        raise Http404("Album Does not exist")'''
    return render(request,"music/details.html",{'album':album})

def favourite(request,album_id):
    album=get_object_or_404(Album,pk=album_id)
    try:
        selected_song=album.song_set.get(pk=request.POST['song'])
    except(KeyError,song.DoesNotExist):
        return render(request,"music/details.html",{'album':album , "error_message":"You did not selected any song",})
    else:
        selected_song.is_favourite=True
        selected_song.save()    
        return render(request,"music/details.html",{'album':album})
# Create your views here.

music/templates/music/details.html
<img src={{album.album_logo}}>

<h1>
    {{album.album_title}}
</h1>
<h2>
    {{album.artist}}
</h2>
{% if error_message %}
    <p><strong>{{error_message}}</strong></p>
{% endif %}

<form action="{% url 'music:favourite' album.id %}" method="POST">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{forloop.counter}}" name="song" value="{{song.id}}">
        <label for=song{{forloop.counter}} >
            {{song.song_title}}
            {%if song.is_favourite %}
                <img src="https://www.google.com/imgres?imgurl=https%3A%2F%2Ff4.bcbits.com%2Fimg%2F0005292398_10.jpg&imgrefurl=https%3A%2F%2Ffavoriterecordings.bandcamp.com%2F&docid=aPY9161BPsLHoM&tbnid=xNbAYuB3QGelpM%3A&vet=10ahUKEwixgtWkjL7lAhUFqY8KHcz0BaYQMwh_KAUwBQ..i&w=1200&h=615&bih=722&biw=1536&q=favorite%20images&ved=0ahUKEwixgtWkjL7lAhUFqY8KHcz0BaYQMwh_KAUwBQ&iact=mrc&uact=8">
            {%endif%}
        </label><br>
    {%endfor%}
    <input type="submit" value="favourite">
</form>

music/templates/music/index.html
{%if all_albums%}
    <h3>
        All Albums
    </h3>
    <ul>
        {% for album in all_albums %}
            <li><a href="{% url  'music:details' album.id %}">{{album.album_title}}</a></li>
        {% endfor %}
    </ul>
{%else%}
    <h2>No Albums Added.Please Add Some</h2>
{%endif%}